sudo: required

services:
  - docker

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - docker pull ubuntu:16.04
  - docker run -i -t ubuntu:16.04 /usr/bin/add-apt-repository main
  - docker run -i -t ubuntu:16.04 /usr/bin/add-apt-repository universe
  - docker run -i -t ubuntu:16.04 /usr/bin/apt update
  - docker run -i -t ubuntu:16.04 /usr/bin/apt-cache policy libcrypto++
  - docker run -i -t ubuntu:16.04 /usr/bin/apt install -y libcrypto++-dev
#  - docker run -i -t ubuntu:16.04 /usr/bin/apt install -y libboost-all-dev

#  - sudo add-apt-repository universe
#  - sudo apt-get -qq update
#  - sudo apt-get install -y libboost-all-dev
#  - sudo apt-cache policy libcrypto++
#  - sudo apt-get install -y libcrypto++-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - ./test_parser